contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://whipperstacker.com/"
languageCode = "en-us"
title = "Whipperstacker"

[permalinks]
post = "/:year/:month/:day/:slug"

[params]
author = "Katrina Owen"
copyright = "Katrina Owen"

[menus]
[[menu.main]]
name = "Archives"
identifier = "archives"
url = "/post/"
